### ISSUE TITLE
community.general.git_config only changes configuration for playbook duration

### ISSUE THREAD

**Issue by pmaresca** [ThePrimeagen/dev#1]
https://github.com/ThePrimeagen/dev/blob/96fa35737c79803876b9fe15a1c96e59d69ca00d/core-setup.yml#L32
It doesn't appear that these steps persist past the playbook run unfortunately.
If you're not interested in maintaining a config file you could probably replace these steps with the ansible equivalent file edit stuff or like `echo stuff >> ~/.gitconfig` or something

**Comment by pmaresca** [comment]
Nevermind that definitely works on my machine...but why not yours?

**Comment by ThePrimeagen** [comment]
Okay, that's good to know.

I will just have to make a ansible command or script.

**Comment by pmaresca** [comment]
are you running this as root or are you intending to run this as user `theprimagen`?

**Comment by ThePrimeagen** [comment]
This might be the problem, I do have the become flag.

I'm going to try to have a separate git set of tasks without become is true and instead become user

**Comment by pmaresca** [comment]
yeah become_user might be the ticket?
```
  - name: user.name for git config
    community.general.git_config:
      name: user.name
      scope: global
      value: "{{ username }}"
    become_user: "{{ username }}"
```
